### ISSUE TITLE
Exception: chain A occurs more than once after cleaning

### ISSUE THREAD

**Issue by jonblack** [cmbi/hommod-rest#18]
HOPE gets this error back from hommod:

```
f551ff58-c277-6de1-376b-4f8830643b0f_HUMAN_40-263:
Traceback (most recent call last):
  File "/usr/src/app/hommod_rest/services/model.py", line 929, in modelProc
    mainTargetSeq, mainDomainRange)
  File "/usr/src/app/hommod_rest/services/model.py", line 468, in _build_for_domain
    self._set_template (mainTemplateID.pdbac)
  File "/usr/src/app/hommod_rest/services/model.py", line 390, in _set_template
    raise Exception ("chain %s occurs more than once after cleaning" % chain)
Exception: chain A occurs more than once after cleaning
```

The position is `227` and the sequence is:

```
MPKKKPTPIQLNPAPDGSAVNGTSSAETNLEALQKKLEELELDEQQRKRLEAFLTQKQKVGELKDDDFEK
ISELGAGNGGVVFKVSHKPSGLVMARKLIHLEIKPAIRNQIIRELQVLHECNSPYIVGFYGAFYSDGEIS
ICMEHMDGGSLDQVLKKAGRIPEQILGKVSIAVIKGLTYLREKHKIMHRDVKPSNILVNSRGEIKLCDFG
VSGQLIDSMANSFVGTRSYMSPERLQGTHYSVQSDIWSMGLSLVEMAVGRYPIPPPDAKELELMFGCQVE
GDAAETPPRPRTPGRPLSSYGMDSRPPMAIFELLDYIVNEPPPKLPSGVFSLEFQDFVNKCLIKNPAERA
DLKQLMVHAFIKRSDAEEVDFAGWLCSTIGLNQPSTPTHAAGV
```

What does this error mean? Is this a bug in hommod or can't hommod do anything about it?

**Comment by cbaakman** [comment]
It means that the template used has an error that hommod can't fix. I reran this job and the error doesn't occur anymore. Probably the template has been added to the black list.
