### ISSUE TITLE
AttributeError: 'TemplateID' object has no attribute 'chain'

### ISSUE THREAD

**Issue by jonblack** [cmbi/hommod-rest#21]
HOPE gets the following error when trying to create a model with hommod:

```
Exception: the following models have failed:
e8ccf04f-7409-2342-9f5d-9b80a1d99517_HUMAN_71-194_1UB1-A:
Traceback (most recent call last):
  File "/usr/src/app/hommod_rest/services/model.py", line 951, in modelProc
    mainTargetSeq, mainDomainRange)
  File "/usr/src/app/hommod_rest/services/model.py", line 472, in _build_for_domain
    mainTemplateID.chain))
AttributeError: 'TemplateID' object has no attribute 'chain'
```

Position is: `143`
Template is: `1UB1_A`
Sequence is:

```
MVAGMLGLREEKSEDQDLQGLKDKPLKFKKVKKDKKEEKEGKHEPVQPSAHHSAEPAEAGKAETSEGSGSAPAVPEASASPKQRRSIIRDRGPMYDDPTLPEGWTRKLKQRKSGRSAGKYDVYLINPQGKAFRSKVELIAYFEKVGDTSLDPNDFDFTVTGRGSPSRREQKPPKKPKSPKAPGTGRGRGRPKGSGTTRPKAATSEGVQVKRVLEKSPGKLLVKMPFQTSPGGKAEGGGATTSTQVMVIKRPGRKRKAEADPQAIPKKRGRKPGSVVAAAAAEAKKKAVKESSIRSVQETVLPIKKRKTRETVSIEVKEVVKPLLVSTLGEKSGKGLKTCKSPGRKSKESSPKGRSSSASSPPKKEHHHHHHHSESPKAPVPLLPPLPPPPPEPESSEDPTSPPEPQDLSSSVCKEEKMPRGGSLESDGCPKEPAKTQPAVATAATAAEKYKHRGEGERKDIVSSSMPRPNREEPVDSRTPVTERVS
```

**Comment by cbaakman** [comment]
This is fixed in https://github.com/cbaakman/hommod-rest/commit/56acfbfa167ee9ef4021c47333641daf9964efd9
