### ISSUE TITLE
TYPE is now 8-bit binary

### ISSUE THREAD

**Issue by jonblack** [cmbi/hommod-rest#45]
HOPE gets the following error from HOMMOD:

```
Exception: the following models have failed:
f1a9c8ce-7bb9-feda-7ad6-f527c0b3de8f_HUMAN_175-298_3NOG-D:
Traceback (most recent call last):
  File "/usr/src/app/hommod_rest/services/model.py", line 967, in modelProc
    main_domain_alignment, main_domain_range)
  File "/usr/src/app/hommod_rest/services/model.py", line 465, in _collect_template
    raise e
IOError: [Errno ftp error] 200 TYPE is now 8-bit binary
```

What is the cause?

**Comment by cbaakman** [comment]
This doesn't seem to happen in the test. However it does happen when running the following commands in python 2.7.12:
```
from urllib import urlopen
s = urlopen('ftp://ftp.wwpdb.org/pub/pdb/data/structures/divided/pdb/cr/pdb1crn.ent.gz').read()
```

**Comment by cbaakman** [comment]
This only seems to occur with urllib, not with urllib2. I'll replace all occurrences in hommod.
