### ISSUE TITLE
Connection to YASARA broken

### ISSUE THREAD

**Issue by jonblack** [cmbi/hommod-rest#46]
HOPE received the following error from HOMMOD:

```
hope.services.types.ServiceError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/src/app/hommod_rest/factory.py", line 96, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/app/hommod_rest/tasks.py", line 38, in create_model
    template_id)
  File "/usr/src/app/hommod_rest/services/model.py", line 849, in modelProc
    self._set_template(chosenTemplateID.pdbac)
  File "/usr/src/app/hommod_rest/services/model.py", line 387, in _set_template
    self.yasara.CleanObj(tempobj)
  File "/deps/yasara/yasara/pym/yasaramodule.py", line 2338, in CleanObj
    run(command[:-1])
  File "/deps/yasara/yasara/pym/yasaramodule.py", line 1012, in run
    if (command.find("\n")==-1): return(process("EXECUTE",command))
  File "/deps/yasara/yasara/pym/yasaramodule.py", line 1006, in process
    result=com.receivemessage(com.RESULT)
  File "/deps/yasara/yasara/pym/yasaramodule.py", line 739, in receivemessage
    (messagetype,datasize)=struct.unpack('ii',self.receive(8))
  File "/deps/yasara/yasara/pym/yasaramodule.py", line 722, in receive
    if (len(chunk)==0): self.reportbrokenconn()
  File "/deps/yasara/yasara/pym/yasaramodule.py", line 692, in reportbrokenconn
    raise RuntimeError("Connection to YASARA broken. Either you exited YASARA manually or it encountered a fatal error")
RuntimeError: Connection to YASARA broken. Either you exited YASARA manually or it encountered a fatal error
```

The following template was used: `{'file_path': None, 'template': {'required_identity': 19.5, 'ac_code': '3JBH', 'chain': 'A', 'identity': 216}}`

This is likely a bug in yasara but it would be nice to know the cause before we email Elmar.

**Comment by cbaakman** [comment]
Looks like a modeling run started with a broken yasara connection, need to find out why yasara's connection was broken in the first place.

**Comment by cbaakman** [comment]
It seems yasara runs out of memory when using this template. We need to give it more. This requires changing the config files.

**Comment by jonblack** [comment]
This is probably a difficult question to answer, but why does it run out of memory with that template? Is it a long sequence? This might be something that can be fixed in yasara.

**Comment by cbaakman** [comment]
It has a high oligomerisation. Many copies of the same protein form a complex. This multiplies the number of atoms in yasara also and makes it need more memory.
