### ISSUE TITLE
ZeroDivisionError: integer division or modulo by zero

### ISSUE THREAD

**Issue by jonblack** [cmbi/hommod-rest#47]
HOPE gets this error from HOMMOD:

```
hope.services.types.ServiceError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/src/app/hommod_rest/factory.py", line 96, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/app/hommod_rest/tasks.py", line 38, in create_model
    template_id)
  File "/usr/src/app/hommod_rest/services/model.py", line 849, in modelProc
    self._set_template(chosenTemplateID.pdbac)
  File "/usr/src/app/hommod_rest/services/model.py", line 416, in _set_template
    return [tempobj, nMolsOligomerized / nMolsUnoligomerized]
ZeroDivisionError: integer division or modulo by zero
```

Create a test for this first. Whenever the denominator is a variable you should always check that it's not zero. I'm not sure if that should be possible but I suspect that it's normal for zero mols to be unoligomerized.

The input sequence is:

```
MMSFVQKGSWLLLALLHPTIILAQQEAVEGGCSHLGQSYADRDVWKPEPCQICVCDSGSVLCDDIICDDQELDCPNPEIPFGECCAVCPQPPTAPTRPPNGQGPQGPKGDPGPPGIPGRNGDPGIPGQPGSPGSPGPPGICESCPTGPQNYSPQYDSYDVKSGVAVGGLAGYPGPAGPPGPPGPPGTSGHPGSPGSPGYQGPPGEPGQAGPSGPPGPPGAIGPSGPAGKDGESGRPGRPGERGLPGPPGIKGPAGIPGFPGMKGHRGFDGRNGEKGETGAPGLKGENGLPGENGAPGPMGPRGAPGERGRPGLPGAAGARGNDGARGSDGQPGPPGPPGTAGFPGSPGAKGEVGPAGSPGSNGAPGQRGEPGPQGHAGAQGPPGPPGINGSPGGKGEMGPAGIPGAPGLMGARGPPGPAGANGAPGLRGGAGEPGKNGAKGEPGPRGERGEAGIPGVPGAKGEDGKDGSPGEPGANGLPGAAGERGAPGFRGPAGPNGIPGEKGPAGERGAPGPAGPRGAAGEPGRDGVPGGPGMRGMPGSPGGPGSDGKPGPPGSQGESGRPGPPGPSGPRGQPGVMGFPGPKGNDGAPGKNGERGGPGGPGPQGPPGKNGETGPQGPPGPTGPGGDKGDTGPPGPQGLQGLPGTGGPPGENGKPGEPGPKGDAGAPGAPGGKGDAGAPGERGPPGLAGAPGLRGGAGPPGPEGGKGAAGPPGPPGAAGTPGLQGMPGERGGLGSPGPKGDKGEPGGPGADGVPGKDGPRGPTGPIGPPGPAGQPGDKGEGGAPGLPGIAGPRGSPGERGETGPPGPAGFPGAPGQNGEPGGKGERGAPGEKGEGGPPGVAGPPGGSGPAGPPGPQGVKGERGSPGGPGAAGFPGARGLPGPPGSNGNPGPPGPSGSPGKDGPPGPAGNTGAPGSPGVSGPKGDAGQPGEKGSPGAQGPPGAPGPLGIAGITGARGLAGPPGMPGPRGSPGPQGVKGESGKPGANGLSGERGPPGPQGLPGLAGTAGEPGRDGNPGSDGLPGRDGSPGGKGDRGENGSPGAPGAPGHPGPPGPVGPAGKSGDRGESGPAGPAGAPGPAGSRGAPGPQGPRGDKGETGERGAAGIKGHRGFPGNPGAPGSPGPAGQQGAIGSPGPAGPRGPVGPSGPPGKDGTSGHPGPIGPPGPRGNRGERGSEGSPGHPGQPGPPGPPGAPGPCCGGVGAAAIAGIGGEKAGGFAPYYGDEPMDFKINTDEIMTSLKSVNGQIESLISPDGSRKNPARNCRDLKFCHPELKSGEYWVDPNQGCKLDAIKVFCNMETGETCISANPLNVPRKHWWTDSSAEKKHVWFGESMDGGFQFSYGNPELPEDVLDVQLAFLRLLSSRASQNITYHCKNSIAYMDQASGNVKKALKLMGSNEGEFKAEGNSKFTYTVLEDGCTKHTGEWSKTVFEYRTRKAVRLPIVDIAPYDIGGPDQEFGVDVGPVCF 
```

And the template is: `{'file_path': None, 'template': {'required_identity': 19.5, 'ac_code': '3HQV', 'chain': 'A', 'identity': 582}}`

**Comment by cbaakman** [comment]
Looks like the template is a C-alpha only structure, this is causing the number of protein chains to be zero. I will make the reported error for this more informative, but hommod cannot build models from this template. Both HOPE and hommod must be adapted to avoid using structures like this.

**Comment by jonblack** [comment]
Can you first chat with @hvenselaar to make sure this is what HOPE expects?

**Comment by cbaakman** [comment]
@hvenselaar says it's OK to keep such structures out.

**Comment by cbaakman** [comment]
I've made sure that only structures with dssp files end up in the set of templates used by hommod. https://github.com/cmbi/hommod-rest/commit/531d7bb61b994d7d252f602ab1621d813abb2a70

However, if the user (like HOPE) submits a structure like 3HQV, hommod has to throw an exception.

**Comment by jonblack** [comment]
What exception is thrown? I assume it's no longer `ZeroDivisionError`?

**Comment by cbaakman** [comment]
It will throw: "No protein chains found in 3HQV"
